# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Miniconda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: TFG.yml
        activate-environment: TFG
        auto-activate-base: false
    - name: Lint with flake8
      run: |
        conda run -n TFG flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        conda run -n TFG flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with unittest
      run: |
        conda run -n TFG python -m unittest discover -s src/test
